### ISSUE TITLE
The document is very confusing 

### ISSUE THREAD

**Issue by ducwp** [TheWebSolver/tws-license-manager-client#5]
Thanks for creating the plugin but I can not make it work.

The document is very confusing.

I have some problems: 
- `const SERVER_URL = 'test.tws';` , What is "test.tws" ? if it a domain why you dont put: yoursite.com, mysite.com, ect? So, I need set **http/https or not http/https?**
- `'slug' => 'my-plugin-with-license-manager-client',` : slug for what?
- `->hash_with( 'server-secret-key' )` : What is "server-secret-key"? Or "server-secret-key" is just "server-secret-key"? 
==> I open the Manager.php and see "The secret key set on the server.", Where to set this string? I have installed "https://github.com/TheWebSolver/tws-license-manager-server" but I dont see this option to set.

After I submit the license key, the notice show: "Request was made outside of license form.", this message from the server.

How to fix it?

Thanks

**Comment by hsehszroc** [comment]
Hello @ducwp,

Most of the information needed to use this plugin is already described [here](https://github.com/TheWebSolver/tws-license-manager-client/blob/master/CLIENT.md). Still, I will try to address your queries.

- `const SERVER_URL = 'test.tws';` -> Yes, this must be a qualified domain name where the [server](https://github.com/TheWebSolver/tws-license-manager-server) plugin is installed.
-- HTTP protocol totally depends on the user. If you are using an SSL site, use `https://`, else `http://`.
-- Highly recommended to use `https://` on the production site.
-- You should configure settings for HTTP. Learn more about it from doc's **REST API** section [here](https://www.licensemanager.at/docs/handbook/plugin-settings/general).
- `'slug' => 'my-plugin-with-license-manager-client'` -> The woocommerce product slug on the server of the plugin sold and that this client is included in.
- `hash_with( 'server-secret-key' )` -> The same secret key generated by **_License Manager for WooCommerce_** plugin.
-- Get crytographics secret by following docs [here](https://www.licensemanager.at/docs/handbook/setup/cryptographic-secrets/) and setup those secret constants by following docs [here](https://www.licensemanager.at/docs/handbook/setup/security/).
-- Then, use same `LMFWC_PLUGIN_SECRET` value on method `hash_with()` replacing _server-secret-key_ with the constant value.
- `Request was made outside of license form.` The reason for this error is because the secret key is missing. Set them and it should work.

Hope this helps.

**Comment by hsehszroc** [comment]
Since there is no reply for over a week, I am going to close this issue.
