### ISSUE TITLE
Client activation

### ISSUE THREAD

**Issue by DesignInvento** [TheWebSolver/tws-license-manager-client#6]
Hello Mate,
Thank you for developing this awesome stuff,
While integration, i am getting error message on activation **Request was made outside of license form.**

please have a look at result output 
```
object(WP_Error)#1702 (3) { ["errors"]=> array(1) { ["license_server_error"]=> array(1) { [0]=> string(41) "Request was made outside of license form." } }
```

test validation is working fine with debug on.

**Comment by hsehszroc** [comment]
Hey @DesignInvento,

Thank you for trying out this plugin. Could you please show the full code used to start the client manager (codes you implemented as shown in `CLIENT.md` file).

I think the issue is caused because of missing `has_with()` method.

**Comment by DesignInvento** [comment]
Hi Thank you for getting back, i have/jad followed the client.md instructions, and same start method beinf used,
`public function start() {
		//echo $this->manager->validate_with()->authenticate_with()->hash_with
		$this->manager
		->validate_with(
			array(
				'license_key' => __( 'Enter a valid license key.', 'tws-license-manager-client' ),
				'email'       => __( 'Enter valid/same email address used at the time of purchase.', 'tws-license-manager-client' ),
				'order_id'    => __( 'Enter same/valid purchase order ID.', 'tws-license-manager-client' ),
				//'slug'        => '',
			)
		)
		->authenticate_with(
			'ck_093706f4c221e7543c7be916218dcd181bcb6f56',
			'cs_02ab8e62e0d5a9199c7d659dc356044ac04972a7',
		)
		->hash_with( 'server-secret-key' )
		->connect_with(
			esc_url( self::SERVER_URL ),
			array(
				'timeout'           => 15,
				'namespace'         => 'lmfwc',
				'version'           => 'v2',

				// set 0 if no HTTPS verification needed (not recommended).
				'verify_ssl'        => 2,

				// Only works if passed as query in BasicAuth authentication (if site has SSL).
				// If set to false, $_SERVER['PHP_AUTH_USER'] & $_SERVER['PHP_AUTH_PW']
				// must be set for authorization on server site.
				// {@filesource license-manager-for-woocommerce/includes/api/Authentication.php}.
				'query_string_auth' => true,
			)
		)
		->disable_form( true );
	}`

**Comment by hsehszroc** [comment]
I can see that you have not added your own secret key and used the default placeholder text instead. Please follow below instructions and check if it works?

- `hash_with( 'server-secret-key' )` -> The same secret key generated by **_License Manager for WooCommerce_** plugin.
-- Get crytographics secret by following docs [here](https://www.licensemanager.at/docs/handbook/setup/cryptographic-secrets/) and setup those secret constants by following docs [here](https://www.licensemanager.at/docs/handbook/setup/security/).
-- Then, use same `LMFWC_PLUGIN_SECRET` value on method `hash_with()` replacing _server-secret-key_ with the constant value.
- `Request was made outside of license form.` The reason for this error is because the secret key is missing. Set them and it should work.

**Comment by DesignInvento** [comment]
ok Thank you for clarification
hash_with( 'server-secret-key' ) was not elaborated well in CLIENT.md please reconfirm may i use LMFWC_PLUGIN_SECRET in hash_with or consumer_secret generated in license manager?

**Comment by hsehszroc** [comment]
You must use `LMFWC_PLUGIN_SECRET` constant value in this case.

**Comment by DesignInvento** [comment]
that's great, would provide feedback, i am palying around the script, have some other issues may needs to implement some checks if in case of activated key removed from server and new license key provided, would be back for further queries. Thank you

**Comment by hsehszroc** [comment]
Sure 🙂

If the current issue is not resolved, please reply. Otherwise, this issue will be assumed resolved and will be closed tomorrow.

Thank you for using this plugin.
